# Generated by Django 4.2.7 on 2024-11-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('CHOISE_1', 'Choise 1'), ('CHOICE_2', 'Choice 2'), ('CHOICE_3', 'Choise 3')], default='CHOISE_1', max_length=9)),
                ('text', models.TextField()),
            ],
        ),
    ]
