# Generated by Django 4.2.7 on 2024-11-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='choice',
            field=models.CharField(choices=[('CHOICE_1', 'Choice 1'), ('CHOICE_2', 'Choice 2'), ('CHOICE_3', 'Choice 3')], default='CHOICE_1', max_length=9),
        ),
    ]
